### ISSUE TITLE
Error when building project from source

### ISSUE THREAD

**Issue by JOE1994** [elfshaker/elfshaker#101]
### Command used for building (built `elfshaker` @ 1755d4fc69d6af519f562f7cdc9a822443c3859a )
```
$ cargo +1.55 build --release --bin elfshaker
```
(as instructed by https://github.com/elfshaker/elfshaker/blob/main/docs/users/installing.md#building-from-source)

### Error Message
```
error[E0658]: use of unstable library feature 'debug_non_exhaustive'
   --> /home/lonelyjoe/.cargo/registry/src/github.com-1ecc6299db9ec823/ureq-2.4.0/src/agent.rs:633:14
    |
633 |             .finish_non_exhaustive()
    |              ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #67364 <https://github.com/rust-lang/rust/issues/67364> for more information
    = help: add `#![feature(debug_non_exhaustive)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'debug_non_exhaustive'
   --> /home/lonelyjoe/.cargo/registry/src/github.com-1ecc6299db9ec823/ureq-2.4.0/src/agent.rs:644:14
    |
644 |             .finish_non_exhaustive()
    |              ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #67364 <https://github.com/rust-lang/rust/issues/67364> for more information
    = help: add `#![feature(debug_non_exhaustive)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ureq` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by peterwaller-arm** [comment]
Thanks for the report! @veselink1 it looks like we're inadvertently pulling in more recent features via a dependency. I guess this would happen because at some point one of us updated the lockfile with a more recent rust. Do you concur? I guess the fix is: 1) Update instructions to use a more recent stable version, and 2) Set `TOOLCHAIN_VERSION=` some specific version in CI so that the build instructions are defended against this breakage.

@JOE1994 please try `rustup install stable` and `rustup default` stable. I assume that will allow it to build, if it does not, please report back.

**Comment by JOE1994** [comment]
Thank you for your prompt feedback!

While trying `rustup default stable` and `rustc --version`,
I realized that my local machine was always using the same quite old version of Rust no matter which version of Rust I choose to use with `rustup` :sweat_smile: 

After totally uninstalling & reinstalling Rust, the below build command now works just fine on my machine!

 ```
$ cargo +1.55 build --release --bin elfshaker
```

I apologize for creating confusion with this non-issue ticket.. Closing..
