### ISSUE TITLE
Using elfshaker as a diff tool for binary files

### ISSUE THREAD

**Issue by layus** [elfshaker/elfshaker#123]
While playing with diffoscope on a shared object file, I had lots of changes due to a few size changes here and there, translating in offsets changes and addresses changes all over the place.

Now I wonder if elfshaker could provide a more condensed diff for such files, even if less readable, by dumping in a somewhat human-readable format the internal data structures representing the compressed output.

Is that theoretically feasible ? Is there any worth in this idea ?

**Comment by peterwaller-arm** [comment]
Thanks for reaching out. Feel free to continue the discussion here even though I've closed the issue for now. It's out of scope for elfshaker, which is primarily a storage/retrieval tool. 

In terms of the crossover with the key concepts from elfshaker/[manyclangs](https://github.com/elfshaker/manyclangs/), though, if you want to avoid having lots of diffs due to addresses changing post-link, instead of diffing the linked shared object, try diffoscope on the object files pre-link. Also, compile with -ffunction-sections and -fdata-sections if you aren't already, which should result in object files where the diffs are smaller, since most of the addresses haven't been written into the binary code yet.

**Comment by layus** [comment]
Thanks for sharing your insights. Do you mean that there is nothing specific in elfshaker or manyclang about binary formats ? With -ffunction-sections and -fdata-sections you get rid of hardcoded offsets, and keep only local offsets, then the binary diff only moves data inside the binary file, but not the data itself, meaning you can "just" reference old data and new data together with offsets in what I see as a chunks table ?

Is there any detail about the compression algorithm ? I did not find it in the source code, despite the source code being pretty small. Is it fair to say that it is akin to standard diffing, except not line-based but byte-based ?

**Comment by peterwaller-arm** [comment]
The biggest win comes from the same effect as a git checkout vs a git repository. Consider the linux repository, it's O(GiB) for a single checkout and the full history of hundreds of thousands of commits is O(GiB) also. The main reason elfshaker/manyclangs gets such a big win is that it's compressing object files where the majority of object files don't change from commit-to-commit. So we take all the unique object files across the full set of object files, sort them by size (which happens to put them near each other in the stream), and then compress them with a good general purpose compressor (zstd). This is analagous to a git packfile. Git does also employ delta'ing, and this was also considered for elfshaker, but the size/speed tradeoff was bad, so bad that it was hard to tricky the general purpose compressor at all (whilst also getting very rapid compression/decompression).

So no, there isn't any diffing. It's 1) find the unique objects, 2) put them into compression streams, 3) have a representation for mapping the filesystem onto the objects. For 3 we assume that not too many objects are changing from commit to commit (otherwise the overall strategy isn't likely to work terribly well in any case). And there for (3) we have a notion of insertions and deletions.

Hope that adds some more context.

**Comment by layus** [comment]
Thank you so much!

It's very clear, and I see now that there isn't any insight into elf files or binary files structure at all in elfshaker. The magic resides elsewhere, so it cannot really get used as a smart, insightful diff tool.

BTW, I think your comment deserves to appear in the main readme, under a new "How does it work ?" section.
