### ISSUE TITLE
The name feels confusing

### ISSUE THREAD

**Issue by KOLANICH** [elfshaker/elfshaker#67]
If I understand right, it is a generic-purpose binary file VCS, not the one parsing ELF format first and then diffing the AST (I don't see anything looking like as an ELF-parsing crate in `Cargo.toml` ). Why not to call it the way to make it clear?

**Comment by peterwaller-arm** [comment]
Hi @KOLANICH, thanks for getting involved.

Your observations are correct, and I agree, the name is not ideal. As a bit of history, when we chose the name it was because we believed we were going to have ELF-format-specific heuristics, but it transpired that they were unnecessary.

Since then though, we have become fond of the name, and it has made an impact on the internet with the name elfshaker even though it's not a perfect fit. We're not really in the frame of mind to consider renaming the project at this stage, so I'm going to close this issue as "unfortunate for now".

That's not to rule out a future rename, and it's also not to rule out introducing heuristics which help ELF files in the future -- although it seems that the usefulness of elfshaker for non-ELF-files is here to stay, and is already a feature we're making use of too.

All the best for now, and feel free to comment even if I'm closing the issue now.
