### ISSUE TITLE
elfshaker can't extract pack w/o loose objects

### ISSUE THREAD

**Issue by marxin** [elfshaker/elfshaker#90]
I've created 100 loose objects and then packed all of them into `all` pack. Later than, I removed loose objects (`rm -rf elfshaker_data/loose/`) and then I can't extract a revision:

```
$ ls
elfshaker_data
$ elfshaker extract all:ff6b2a3e70562f4250504fc10aa83eeb98e653d7
[WARN (main) 10.36703ms]: Expected file "/tmp/elfshaker/usr/local/share/man/man1/gcov-tool.1" to be present!
[ERROR (main) 10.766437ms]: *FATAL*: Some files in the repository have been removed or modified unexpectedly! You can use --force to skip this check, but this might result in DATA LOSS!
```

Elfshaker repo: https://splichal.eu/tmp/elfshaker-repo.tar

**Comment by peterwaller-arm** [comment]
Hi @marxin - can you provide a sequence of commands which reproduces the issue?

My literal read of the error, assuming it is correct, is that `./usr/local...` doesn't exist. And I assume elfshaker is expecting this because there is a HEAD file which points at a snapshot which was previously checked out. So my theory is that you have not just deleted the loose objects but also the other extracted files.

The reason it works this way is that elfshaker has an optimization for extracts in a directory where there is already something extracted: it only updates the files which need updating relative to the old snapshot. As part of the optimization though, it checks that files it expects to be there.

Is that correct, does that make sense? Is there some way we might improve the error message I'd appreciate your input there.

@veselink1 I've also hit this case a few times and had to '--force' my way out of the situation. My recollection is that it is this way because if things are changed since we last did an `extract` then really all bets are off and the user has to make a decision about what to do (for example they may want to start with an empty directory).

I wonder if a minor UX improvement here would be to have an exception for the empty directory (other than elfshaker_data) case: in that case it's clear the user wants to populate stuff, even if the elfshaker_data/HEAD points somewhere.

**Comment by marxin** [comment]
> Is that correct, does that make sense? Is there some way we might improve the error message I'd appreciate your input there.

My sequence of commands was that I `store`d 100 snapshots, and created a pack out of them. Then I removed the loose objects (`rm -rf elfshaker_data/loose/`) and extracted a random snapshot. That was when I saw the error. And yes, my HEAD was very likely pointing to a loose object.

Anyway, I can confirm that using `--force` fixes my problem. Feel free to close this issue.

**Comment by peterwaller-arm** [comment]
To clarify, at some point `/tmp/elfshaker/usr/local/share/man/man1/gcov-tool.1` existed, yes? Or at least, this path existed when a store was run. And then at some point it doesn't? The reason this file doesn't exist is important to me, and you are suggesting that you haven't removed it (or caused it to not exist).

I would like to know why there is a `HEAD` file which which implies this file should exist when it does not, because it is weakly suggesting some kind of data loss, and it seems important to rule out that this is arising from elfshaker. Can you confirm?

**Comment by marxin** [comment]
> To clarify, at some point `/tmp/elfshaker/usr/local/share/man/man1/gcov-tool.1` existed, yes?

The file is present all in all snapshots. But the message is result of the fact that I removed entire `usr` folder before I called the `elfshaker extract all:ff6b2a3e70562f4250504fc10aa83eeb98e653d7` command.

**Comment by peterwaller-arm** [comment]
> the message is result of the fact that I removed entire usr folder before I called the elfshaker extract
Previously:
>> Then I removed the loose objects (rm -rf elfshaker_data/loose/) and extracted a random snapshot

Thanks for clarifying. It was unclear to me that you had deleted files from the working directory, in which case it looks like everything is functioning as intended.

I've filed #92 for a minor UX improvement here when the worktree is empty.
